version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: database
    networks:
      - backend-network

  backend:
    image: kartago124/product-backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - backend-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/database

networks:
  backend-network:
    driver: bridge
