version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./CloudDB-User.sql:/docker-entrypoint-initdb.d/CloudDB-User.sql


  app:
    build: .
    container_name: node-app
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql-data:
