services:
  api-order:
    image: flts123/api-order
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/apis/order
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/order
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
