services:
  api-order:
    image: flts123/api-order
    volumes:
      - ./:/apis/order
    environment:
      DATABASE_URL: postgresql://postgres:postgres@52.204.117.43:5432/order
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
