version: '3.9'
services:
  product-backend:
    image: kartago124/product-backend
    container_name: product-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://52.204.117.43:27017/database
    networks:
      - backend-network

  api-order:
    image: kartago124/order-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@52.204.117.43:5432/order
    networks:
      - backend-network

  user-backend:
    build: ./user
    container_name: user-backend
    env_file:
      - ./user/.env
    ports:
      - "8081:8081"
    environment:
      DB_HOST: 52.204.117.43
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: userdb
    networks:
      - backend-network

  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "3000:3000"
    networks:
      - backend-network
    depends_on:
      - api-order
      - product-backend
      - user-backend

networks:
  backend-network:
    driver: bridge
